# Generated by Django 4.1.3 on 2022-12-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.CharField(default='anderson', max_length=100),
        ),
    ]
