# Generated by Django 4.1.3 on 2023-01-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_profile_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='degree',
            new_name='website',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='about_you',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='school',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='university',
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='country', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.CharField(default='username', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(default='username', max_length=50),
        ),
    ]
