# Generated by Django 4.1.3 on 2023-01-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_degree_profile_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_exp',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience_title',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
