# Generated by Django 4.1.3 on 2023-01-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_profile_company_profile_company_exp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aboutyou',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
