# Generated by Django 4.1.3 on 2023-01-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_profile_aboutyou'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='htmlskill',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
