# Generated by Django 4.1.3 on 2023-01-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_profile_htmlskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='codingskill',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='cskill',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='cssskill',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='dbmsskill',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='javascriptskill',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='pythonskill',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
