# Generated by Django 4.1.3 on 2023-01-08 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_profile_codingskill_profile_cskill_profile_cssskill_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cskill',
            new_name='csskill',
        ),
    ]
